feat(frontend): add inline transliterations to source gurmukhi
shabados/presenter pull request #607
Opened 2020-10-21 16:23 UTC by bhajneet

this can be used in camps to help teach gurmukhi from it's english equivalent

note: it is no longer possible to justify gurmukhi/source line (center text and primary pause wrapping continue to work fine)

Fixes #248

### Summary of PR

![image](https://user-images.githubusercontent.com/14130567/96747941-eb61a800-1396-11eb-8f45-440db207afd7.png)

### Tests for unexpected behavior
- various settings combos juggled around in browser

### Time spent on PR
- 4 to 5 hours

### Linked issues
Fix #248

### Reviewers
@Harjot1Singh 

### Comments
I can also add a "guide" option such as "Column Lines for Inline Transliterations", it would perhaps look something like this: 

![image](https://user-images.githubusercontent.com/14130567/96748779-008b0680-1398-11eb-9af2-f8f2934c163d.png)

2020-10-21 16:25 UTC, bhajneet commented
@sarabveer once this is merged and GU is released, I can add laghu/deeragh numberings to each word

2020-10-21 16:38 UTC, Harjot1Singh commented
Justifying doesn't work in this mode only, correct? Looks cool! Will review properly soon.

2020-10-21 17:07 UTC, bhajneet commented
I actually did not test justify source line without transliterations. I think I should be able to get that to work perhaps, by shuffling around CSS at worst.

2020-10-22 20:47 UTC, Harjot1Singh commented
Unable to run this PR.

`Attempted import error: 'faCompressAlt' is not exported from '@fortawesome/free-solid-svg-icons'.`

Did you have #605 checked out before?

2020-10-23 14:19 UTC, Harjot1Singh commented
![image](https://user-images.githubusercontent.com/1184274/97015108-138e0a00-1543-11eb-8724-58c153073aa6.png)

Standard layout is broken

2020-10-23 14:20 UTC, Harjot1Singh commented on app/frontend/src/Presenter/Line.css
> +  .source.withTransliterations
lol did prettier do this?

2020-10-23 14:27 UTC, Harjot1Singh requested changes
Pretty cool feature!

1) Fix the standard layout, appears to be broken
2) Some refactoring can be done
  - No need to regenerate the transliteration for each word, given that are transliterations are 1-1 word mappings
  - Repeated code, the only difference appears to be positioning. Extract this chunk. Can help you with this if need be.

2020-10-23 14:27 UTC, Harjot1Singh commented on app/frontend/src/Presenter/Line.js
> +                      {inlineTransliteration ? transliterations.filter( isString )
Use `inlineTransliteration &&` instead of a ternary that returns nothing

2020-10-23 14:27 UTC, Harjot1Singh commented on app/frontend/src/Presenter/Line.js
> +          <div className={inlineTransliteration ? 'source withTransliterations' : 'source'}>
Use the `classNames` lib function instead of building classnames like this

2020-10-23 14:27 UTC, Harjot1Singh commented on app/frontend/src/Presenter/Line.js
> +                            {`${dynamicallyTransliterate( toUnicode( word ) )}`}
Why not use the actual transliteration that's there and just grab the `i`th transliterated word?

2020-10-23 14:27 UTC, Harjot1Singh commented on app/frontend/src/Presenter/Line.js
> +          .map( ( [ name, transliteration, fontSize ] ) => (
Code repetition - is the only thing different the `CSSTransition`?

2020-10-23 17:32 UTC, bhajneet commented on app/frontend/src/Presenter/Line.js
> +                            {`${dynamicallyTransliterate( toUnicode( word ) )}`}
I would take the translit, split by semicolon, then split by space, then use the `i`th 

I did this before, thought it was not a good solution, but can do if you like

2020-10-23 17:34 UTC, bhajneet commented on app/frontend/src/Presenter/Line.css
> +  .source.withTransliterations
yes, and I thought it more readable

2020-10-23 17:35 UTC, bhajneet commented
added another option, need to fix the css in some layouts, not sure how it broke -- will take a look on sunday

2020-10-24 04:22 UTC, bhajneet commented on app/frontend/src/Presenter/Line.js
> +                            {`${dynamicallyTransliterate( toUnicode( word ) )}`}
Also I just remembered, this won't work for lines with mool mantar, ik oankaar has a space in between

2020-10-27 16:17 UTC, Harjot1Singh commented
![image](https://user-images.githubusercontent.com/1184274/97330220-df328a80-186f-11eb-83a9-dbeafe953443.png)
Do we want column guides when there are no inline transliterations?

2020-10-28 02:21 UTC, bhajneet commented
Yes, because we may use them for syllabic weight representation, dictionary results, one-to-one translations, etc besides just translit

They can also be used as an alternate to rang chhed / pad chhed for larrivaar assist (if CSS is done properly)

2020-11-03 00:34 UTC, Harjot1Singh commented
@bhajneet please check this out and try to break it. There's relatively significant code restructuring and simplification on some parts, to do with trnaslations and transliterations.

2020-11-03 00:37 UTC, Harjot1Singh commented
![image](https://user-images.githubusercontent.com/1184274/97934145-b8db8600-1d6c-11eb-985c-2122fcae7de9.png)

I'm unable to push because of this?

2020-11-03 00:52 UTC, Harjot1Singh commented
Moved to #623

2020-11-03 00:52 UTC, closed without merging